/**
 * Rede credenciada extraída dos PDFs Select e Hapvida (OCR + correções de leitura).
 * Fonte: rede select.pdf e rede hapvida.pdf — tabelas "Rede Credenciada / Principais hospitais e laboratórios".
 */
(function (global) {
  'use strict';

  /** @typedef {{ nome: string, planos: (string|null)[] }} Hospital */
  /** @typedef {{ nome: string, itens: Hospital[] }} Regiao */
  /** @typedef {{ planos: string[], legenda: Record<string,string>, regioes: Regiao[] }} Rede */

  /** @type {Rede} */
  const REDE_SELECT = {
    planos: ['SP 100', 'SP 200', 'Premium 110', 'Premium 120'],
    legenda: {
      H: 'Internação hospitalar',
      M: 'Maternidade',
      PSA: 'Pronto-socorro adulto',
      PSP: 'Pronto-socorro infantil/pediátrico',
      LAB: 'Laboratório',
    },
    regioes: [
      {
        nome: 'São Paulo — Centro',
        itens: [
          { nome: 'Cruz Azul de São Paulo', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'Leforte — Liberdade', planos: ['H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP'] },
          { nome: 'BP Mirante', planos: [null, null, null, 'H,PSA'] },
          { nome: 'H Nove de Julho', planos: [null, null, null, 'H,PSA'] },
          { nome: 'Samaritano — Paulista', planos: [null, null, null, 'H,PSA'] },
          { nome: 'Sta Catarina', planos: [null, null, 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
        ],
      },
      {
        nome: 'São Paulo — Zona Sul',
        itens: [
          { nome: 'Dom Alvarenga', planos: ['H,M,PSA', 'H,M,PSA', 'H,M,PSA', 'H,M,PSA'] },
          { nome: 'São Camilo — Ipiranga', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'Sta Rita', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'Cto de Tratamento Bezerra de Menezes', planos: [null, null, 'H,PSA', 'H,PSA'] },
          { nome: 'Edmundo Vasconcelos', planos: [null, null, 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'Santa Joana', planos: [null, null, null, 'H,M,PSA'] },
          { nome: 'Sta Paula', planos: [null, null, null, 'H'] },
        ],
      },
      {
        nome: 'São Paulo — Zona Oeste',
        itens: [
          { nome: 'Albert Sabin — Lapa', planos: [null, null, null, 'H'] },
          { nome: 'Clínicas FMUSP — Instituto Central', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'Leforte — Morumbi', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'São Camilo — Pompéia', planos: [null, null, 'H,PSA,PSP', 'H,PSA,PSP'] },
        ],
      },
      {
        nome: 'São Paulo — Zona Leste',
        itens: [
          { nome: 'Hospital São Miguel', planos: ['H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP'] },
          { nome: 'IBCC', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'São Miguel — Ermelino Matarazzo', planos: ['H,M,PSA', 'H,M,PSA', 'H,M,PSA', 'H,M,PSA'] },
          { nome: 'Sta Marcelina', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'H Monte Cristo — SP', planos: [null, 'H', null, 'H'] },
          { nome: 'Sta Virginia', planos: ['H,M,PSA', null, 'H,M,PSA', null] },
        ],
      },
      {
        nome: 'São Paulo — Zona Norte',
        itens: [
          { nome: 'H e Mat NS do Rosário', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'Hospital São Camilo — Santana', planos: ['H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP'] },
          { nome: 'HSANP', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
        ],
      },
      {
        nome: 'Grande SP',
        itens: [
          { nome: 'Clin Maia (Psiquiatria) — Itapecerica da Serra', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'Instituto de Olhos CRO', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'H e Mat Nova Vida', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'H e Mat Cruzeiro do Sul', planos: ['H,M,PSA,PSP', null, 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
        ],
      },
      {
        nome: 'ABCD',
        itens: [
          { nome: 'H Christóvão da Gama — Diadema', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'H Mater Christovão da Gama', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'H Intermédica do AB', planos: ['H,M,PSA', 'H,M,PSA', 'H,M,PSA', 'H,M,PSA'] },
          { nome: 'H Olhos ABC — São Bernardo do Campo', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'Casa de Saúde Stella Maris', planos: [null, null, 'H,M,PSA', 'H,M,PSA'] },
        ],
      },
      {
        nome: 'Alto Tietê',
        itens: [
          { nome: 'H e Mat Mogi Mater', planos: ['H,M,PSA', 'H,M,PSA', 'H,M,PSA', 'H,M,PSA'] },
          { nome: 'H Saint Nicholas', planos: ['H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP', 'H,PSA,PSP'] },
          { nome: 'Sta Casa', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'H Santana', planos: ['H,M,PSA,PSP', null, 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
        ],
      },
      {
        nome: 'Campinas e Região',
        itens: [
          { nome: 'H Rumo Certo', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'Leonardo da Vinci — Atibaia', planos: ['H,PSA', 'H,PSA', 'H,PSA', 'H,PSA'] },
        ],
      },
      {
        nome: 'Sorocaba e Região',
        itens: [
          { nome: 'Notrecare — Sorocaba', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
        ],
      },
      {
        nome: 'Vale do Paraíba',
        itens: [
          { nome: 'Antoninho da Rocha Marmo — São José dos Campos', planos: [null, null, 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'São José dos Campos', planos: [null, null, null, 'H,PSA'] },
        ],
      },
      {
        nome: 'Interior',
        itens: [
          { nome: 'H Araraquara', planos: ['H,PSA', null, 'H,PSA', 'H,PSA'] },
          { nome: 'H São Francisco — Unid Netto Campello (Sertãozinho)', planos: ['H,M,PSA,PSP', null, 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
          { nome: 'HRCPP — Presidente Prudente', planos: ['H,PSA', 'H,PSA', null, 'H,PSA'] },
          { nome: 'Sta Casa de Presidente Prudente', planos: [null, null, 'H,PSA', 'H,PSA'] },
          { nome: 'Presidente Venceslau', planos: [null, null, null, 'H,M,PSA'] },
        ],
      },
      {
        nome: 'Baixada Santista',
        itens: [
          { nome: 'Casa de Saúde', planos: ['H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP', 'H,M,PSA,PSP'] },
        ],
      },
      {
        nome: 'Laboratórios',
        itens: [
          { nome: 'A+ (Grupo Fleury) — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Alpha Diag — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Alta', planos: [null, null, 'LAB', 'LAB'] },
          { nome: 'Bio Lab', planos: [null, null, 'LAB', 'LAB'] },
          { nome: 'BR Diagnóstico', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Delboni Auriemo', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Deliberato', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Exame Brasil', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Genoa Biotecnologia', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Labi Exames', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Lavoisier — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Marlene Spir', planos: [null, null, 'LAB', 'LAB'] },
          { nome: 'Oswaldo Cruz — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Platta — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Sabin Diagnóstico — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Salomão e Zoppi', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Sancet', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Sonilab', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Vale Clin — SP', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
          { nome: 'Vital Lab', planos: ['LAB', 'LAB', 'LAB', 'LAB'] },
        ],
      },
    ],
  };

  /** @type {Rede} */
  const REDE_HAPVIDA = {
    planos: ['Nosso Médico RMSP', 'Smart UP', 'Smart UP 50+'],
    legenda: {
      AMB: 'Ambulatório / clínica',
      H: 'Internação hospitalar',
      PA: 'Pronto atendimento',
      PS: 'Pronto-socorro geral',
      PSA: 'Pronto-socorro adulto',
      PSP: 'Pronto-socorro infantil/pediátrico',
      LAB: 'Laboratório',
      M: 'Maternidade',
    },
    regioes: [
      {
        nome: 'São Paulo — Centro',
        itens: [
          { nome: 'CC NDI — Herminio Lemos (Cambuci)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Vila Monumento', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Qualivida — Santa Cecília', planos: ['AMB', 'AMB', 'AMB'] },
        ],
      },
      {
        nome: 'São Paulo — Zona Leste',
        itens: [
          { nome: 'CC NDI — Itaquera (Vila Carmosina)', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — São Miguel (São Miguel Paulista)', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — Tatuapé (Vila Azevedo)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Anália Franco (Vila Formosa)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CM NDI — São Gabriel (Penha de França)', planos: ['PA', 'PA', 'PA'] },
          { nome: 'H Anália Franco', planos: ['PSA', 'H,PSA', 'H,PSA'] },
          { nome: 'H Salvalus', planos: ['PS', 'H,M,PS', 'H,PS'] },
        ],
      },
      {
        nome: 'São Paulo — Zona Oeste',
        itens: [
          { nome: 'CC NDI — Lapa', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Pompéia', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CM NDI Zona Oeste (Butantã)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Barra Funda', planos: ['LAB', 'LAB', null] },
        ],
      },
      {
        nome: 'São Paulo — Zona Sul',
        itens: [
          { nome: 'CC NDI — Interlagos (Jardim Umuarama)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Unid Ipiranga (Vila Monumento)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Zona Sul (Santo Amaro)', planos: ['PA', 'PA', 'PA'] },
          { nome: 'H e Mat Bosque da Saúde', planos: ['PS', 'PS', 'PS'] },
          { nome: 'API Psiquiátrica Integrada (Indianópolis)', planos: [null, 'H', 'H'] },
          { nome: 'Rim e Hipertensão (Vila Clementino)', planos: [null, 'H,PS', 'H,PS'] },
        ],
      },
      {
        nome: 'São Paulo — Zona Norte',
        itens: [
          { nome: 'CM NDI — Santana (Canindé)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'H e Mat NS do Rosário (Vila Maria Alta)', planos: ['PS', 'H,PS', 'H,PS'] },
        ],
      },
      {
        nome: 'Grande SP',
        itens: [
          { nome: 'CC NDI — Alphaville (Barueri)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Carapicuíba', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — Cotia', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — Itapevi', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — Osasco', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Santo Antônio (Osasco)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI — Taboão da Serra', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI Autonomistas (Osasco)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Guarulhos II — Vila Hulda', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Guarulhos III — Ponte Grande', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Unid Avançada Osasco', planos: ['PA', 'PA', 'PA'] },
          { nome: 'H e Mat Cruzeiro do Sul', planos: ['PSA', 'H,M,PSA', 'H,M,PS'] },
          { nome: 'H e Mat Guarulhos', planos: ['PS', 'H,M,PS', 'H,M,PS'] },
          { nome: 'H e Mat Nova Vida (Itapevi)', planos: ['PS', 'PS', 'PS'] },
          { nome: 'PSA Taboão da Serra', planos: ['PSA', 'PS', 'PS'] },
          { nome: 'PS Barueri', planos: ['PA', 'PA', 'PA'] },
        ],
      },
      {
        nome: 'ABCD',
        itens: [
          { nome: 'CC NDI — Mauá', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — Ribeirão Pires', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — SCS (São Caetano do Sul)', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI Diadema — Centro', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI Notre Lucas Garcéz (São Bernardo)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Santo André 2 — Campestre', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI Santo André 3', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI SBC — Unid 1', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC NDI SBC — Unid 4', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CC São Bernardo III — SBC', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'CM NDI — ABC (São Bernardo)', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'H Notrecare ABC', planos: ['PSP', 'H,M,PS', 'H,M,PS'] },
          { nome: 'H São Bernardo', planos: ['PSA', 'PS', 'PS'] },
          { nome: 'Sta Casa — Cto Bezerra de Menezes (SBC)', planos: [null, 'H,PSA', 'H,PSA'] },
        ],
      },
      {
        nome: 'Alto Tietê',
        itens: [
          { nome: 'CC NDI Soaria', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC NDI — Mogi das Cruzes', planos: ['PA', 'PA', 'PA'] },
          { nome: 'CC Suzano', planos: ['AMB', 'AMB', 'AMB'] },
          { nome: 'H Santana', planos: ['PS', 'H,M,PS', 'H,M,PS'] },
          { nome: 'H Sta Maria de Suzano', planos: [null, 'H,PSP', 'H,PSP'] },
          { nome: 'Sta Casa Guararema', planos: ['H,PS', 'PS', 'PS'] },
        ],
      },
      {
        nome: 'Campinas e Região',
        itens: [
          { nome: 'CC NDI — Andrade Neves I', planos: ['AMB', null, 'AMB'] },
          { nome: 'CC NDI — Andrade Neves II', planos: ['AMB', null, 'AMB'] },
          { nome: 'CC NDI — Itapura', planos: ['AMB', null, 'AMB'] },
          { nome: 'CC NDI — Várzea Paulista', planos: ['PA', null, 'PA'] },
          { nome: 'H Paulo Sacramento', planos: ['M,PS', null, 'M,PS'] },
          { nome: 'H Renascença Campinas', planos: ['PS', null, 'H,M,PS'] },
          { nome: 'Hospital Seara', planos: ['PS', null, 'H,PS'] },
        ],
      },
      {
        nome: 'Baixada Santista',
        itens: [
          { nome: 'CC NDI Frei Galvão — São Vicente', planos: ['PA', null, 'PA'] },
          { nome: 'H Frei Galvão — Santos', planos: ['PS', null, 'H,PS'] },
          { nome: 'H São Lucas de Santos', planos: [null, null, 'H,PS'] },
        ],
      },
      {
        nome: 'Sorocaba e Região',
        itens: [
          { nome: 'CC GNDI Qualivida', planos: ['AMB', null, 'AMB'] },
          { nome: 'CC NDI — Tavuvu', planos: ['AMB', null, 'AMB'] },
          { nome: 'CC NDI — Rodrigues Pacheco', planos: ['AMB', null, 'AMB'] },
          { nome: 'CC NDI — Sorocaba', planos: ['AMB', null, 'AMB'] },
          { nome: 'H Modelo Sorocaba', planos: ['PS', null, 'M,PS'] },
          { nome: 'Notrecare — Sorocaba', planos: [null, null, 'M,PS'] },
          { nome: 'CC NDI Itu — Centro', planos: ['PA', null, 'PA'] },
          { nome: 'SPA', planos: [null, 'H,PS', 'H,PS'] },
          { nome: 'H Oftalmológico de Sorocaba', planos: [null, null, 'H'] },
        ],
      },
      {
        nome: 'Laboratórios',
        itens: [
          { nome: 'Alpha', planos: ['LAB', null, 'LAB'] },
          { nome: 'Anchieta', planos: ['LAB', null, 'LAB'] },
          { nome: 'Bco Sangue', planos: ['LAB', null, 'LAB'] },
          { nome: 'Bio Campos', planos: ['LAB', null, 'LAB'] },
          { nome: 'Biocenter — SP', planos: ['LAB', null, 'LAB'] },
          { nome: 'Bioclinic', planos: ['LAB', null, 'LAB'] },
          { nome: 'Biolabor', planos: ['LAB', null, 'LAB'] },
          { nome: 'Biológico', planos: ['LAB', null, 'LAB'] },
          { nome: 'Cardoso de Almeida', planos: ['LAB', null, 'LAB'] },
          { nome: 'Carlos Chagas', planos: ['LAB', null, 'LAB'] },
          { nome: 'Dasa', planos: ['LAB', null, 'LAB'] },
          { nome: 'Diagnos', planos: ['LAB', null, 'LAB'] },
          { nome: 'DMS Burnier', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Femme', planos: ['LAB', null, 'LAB'] },
          { nome: 'Genoa Biotecnologia', planos: ['LAB', null, 'LAB'] },
          { nome: 'Gonzaga', planos: ['LAB', null, 'LAB'] },
          { nome: 'Hormon', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Itulab', planos: [null, null, 'LAB'] },
          { nome: 'Jablonka', planos: ['LAB', null, 'LAB'] },
          { nome: 'Lavoisier — SP', planos: ['LAB', null, 'LAB'] },
          { nome: 'Locus', planos: ['LAB', null, 'LAB'] },
          { nome: 'Máximo', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Notrelabs', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Pasteur', planos: ['LAB', null, 'LAB'] },
          { nome: 'Pathos', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Platta — SP', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Sabin Diagnóstico — SP', planos: ['LAB', null, 'LAB'] },
          { nome: 'Salomão e Zoppi', planos: ['LAB', null, 'LAB'] },
          { nome: 'Senne Liquor', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Sete Mais', planos: ['LAB', null, 'LAB'] },
          { nome: 'SMD', planos: ['LAB', null, 'LAB'] },
          { nome: 'Souza Arêas', planos: ['LAB', null, 'LAB'] },
          { nome: 'UMDI', planos: ['LAB', 'LAB', 'LAB'] },
          { nome: 'Vital Lab', planos: ['LAB', null, 'LAB'] },
        ],
      },
    ],
  };

  const MAPA_UNIDADES = [
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Herminio Lemos',
      endereco: 'Rua Hermínio Lemos, 385, Cambuci, São Paulo, SP',
      lat: -23.5684,
      lng: -46.6214,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Vila Monumento',
      endereco: 'Avenida Dom Pedro I, 372, Vila Monumento, São Paulo, SP',
      lat: -23.5755,
      lng: -46.6115,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Qualivida - Santa Cecilia',
      endereco: 'Avenida Angélica, 381, Santa Cecília, São Paulo, SP',
      lat: -23.5358,
      lng: -46.6548,
    },
    {
      operadora: 'hapvida',
      nome: 'H Inglês',
      endereco: 'Rua Sílvia, 193, Bela Vista, São Paulo, SP',
      lat: -23.5647,
      lng: -46.6496,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Itaquera',
      endereco: 'Avenida Itaquera, 7426, Vila Carmosina, São Paulo, SP',
      lat: -23.5601,
      lng: -46.4674,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - São Miguel',
      endereco: 'Rua Tenente Luís Fernando Lobo, 51, São Miguel Paulista, São Paulo, SP',
      lat: -23.4981,
      lng: -46.4442,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Tatuapé',
      endereco: 'Rua Platina, 215, Tatuapé, São Paulo, SP',
      lat: -23.5413,
      lng: -46.5746,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Anália Franco',
      endereco: 'Rua Acuruí, 493, Vila Formosa, São Paulo, SP',
      lat: -23.5635,
      lng: -46.5623,
    },
    {
      operadora: 'hapvida',
      nome: 'CM NDI - São Gabriel',
      endereco: 'Avenida Amador Bueno da Veiga, 195, Penha de França, São Paulo, SP',
      lat: -23.5242,
      lng: -46.5448,
    },
    {
      operadora: 'hapvida',
      nome: 'H Anália Franco',
      endereco: 'Avenida Montemagno, 241, Vila Formosa, São Paulo, SP',
      lat: -23.5678,
      lng: -46.5611,
    },
    {
      operadora: 'hapvida',
      nome: 'H Salvadus',
      endereco: 'Rua Bresser, 1954, Mooca, São Paulo, SP',
      lat: -23.5532,
      lng: -46.6083,
    },
    {
      operadora: 'hapvida',
      nome: 'IBCC',
      endereco: 'Avenida Alcântara Machado, 2576, Mooca, São Paulo, SP',
      lat: -23.5518,
      lng: -46.5982,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Lapa',
      endereco: 'Rua George Smith, 287, Lapa, São Paulo, SP',
      lat: -23.5218,
      lng: -46.7027,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Pompéia',
      endereco: 'Avenida Pompeia, 1165, Pompéia, São Paulo, SP',
      lat: -23.5332,
      lng: -46.6859,
    },
    {
      operadora: 'hapvida',
      nome: 'CM NDI Zona Oeste',
      endereco: 'Rua M.M.D.C, 18, Butantã, São Paulo, SP',
      lat: -23.5714,
      lng: -46.7078,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Barra Funda',
      endereco: 'Avenida Francisco Matarazzo, 612, Água Branca, São Paulo, SP',
      lat: -23.5273,
      lng: -46.6738,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Interlagos',
      endereco: 'Avenida Interlagos, 2825, Jardim Umuarama, São Paulo, SP',
      lat: -23.6826,
      lng: -46.6908,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Unid Ipiranga',
      endereco: 'Rua Maurício de Castilho, 416, Ipiranga, São Paulo, SP',
      lat: -23.5855,
      lng: -46.6111,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Zona Sul',
      endereco: 'Avenida João Dias, 76, Santo Amaro, São Paulo, SP',
      lat: -23.6453,
      lng: -46.7032,
    },
    {
      operadora: 'hapvida',
      nome: 'H e Mat Bosque da Saúde',
      endereco: 'Avenida Bosque da Saúde, 1926, Saúde, São Paulo, SP',
      lat: -23.6136,
      lng: -46.6214,
    },
    {
      operadora: 'hapvida',
      nome: 'API Psiquiátrica Integrada',
      endereco: 'Avenida Indianópolis, 1903, Indianópolis, São Paulo, SP',
      lat: -23.6108,
      lng: -46.6558,
    },
    {
      operadora: 'hapvida',
      nome: 'Rim e Hipertensão',
      endereco: 'Rua Borges Lagoa, 960, Vila Clementino, São Paulo, SP',
      lat: -23.5979,
      lng: -46.6433,
    },
    {
      operadora: 'hapvida',
      nome: 'CM NDI - Santana',
      endereco: 'Avenida Cruzeiro do Sul, 2977, Santana, São Paulo, SP',
      lat: -23.5041,
      lng: -46.6247,
    },
    {
      operadora: 'hapvida',
      nome: 'H e Mat N S do Rosário',
      endereco: 'Rua Doutor Edson de Melo, 357, Vila Maria Alta, São Paulo, SP',
      lat: -23.5134,
      lng: -46.5862,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Alphaville',
      endereco: 'Alameda Amazonas, 329, Alphaville Industrial, Barueri, SP',
      lat: -23.5005,
      lng: -46.8483,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Carapicuiba',
      endereco: 'Avenida Tâmara, 311, Centro, Carapicuíba, SP',
      lat: -23.5233,
      lng: -46.8372,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Cotia',
      endereco: 'Avenida Professor Joaquim Barreto, 74, Centro, Cotia, SP',
      lat: -23.6015,
      lng: -46.9183,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Itapevi',
      endereco: 'Rua Agnaldo José dos Santos, 27, Vila Aurora, Itapevi, SP',
      lat: -23.5487,
      lng: -46.9324,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Osasco',
      endereco: 'Rua Paulo Lício Rizzo, 66, Centro, Osasco, SP',
      lat: -23.5356,
      lng: -46.7792,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Santo Antônio',
      endereco: 'Avenida Santo Antonio, 1905, Vila Osasco, Osasco, SP',
      lat: -23.5457,
      lng: -46.7923,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI - Taboão da Serra',
      endereco: 'Estrada São Francisco, 1200, Jardim Henriqueta, Taboão da Serra, SP',
      lat: -23.6214,
      lng: -46.7758,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Autonomistas',
      endereco: 'Avenida dos Autonomistas, 2606, Centro, Osasco, SP',
      lat: -23.5395,
      lng: -46.7844,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Guarulhos I - Vila Hulda',
      endereco: 'Avenida Doutor Timóteo Penteado, 1168, Vila Hulda, Guarulhos, SP',
      lat: -23.4567,
      lng: -46.5293,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Guarulhos II - Ponte Grande',
      endereco: 'Rua Cabo João Teruel Fregoni, 555, Ponte Grande, Guarulhos, SP',
      lat: -23.4862,
      lng: -46.5051,
    },
    {
      operadora: 'hapvida',
      nome: 'CC NDI Unid Avançada Osasco',
      endereco: 'Avenida dos Autonomistas, 2621, Centro, Osasco, SP',
      lat: -23.5394,
      lng: -46.7848,
    },
    {
      operadora: 'hapvida',
      nome: 'H e Mat Cruzeiro do Sul',
      endereco: 'Avenida dos Autonomistas, 2502, Centro, Osasco, SP',
      lat: -23.548,
      lng: -46.7608,
    },
    {
      operadora: 'hapvida',
      nome: 'H e Mat Guarulhos',
      endereco: 'Avenida Tiradentes, 1015, Jardim Santa Edwirges, Guarulhos, SP',
      lat: -23.4651,
      lng: -46.5218,
    },
    {
      operadora: 'hapvida',
      nome: 'H e Mat Nova Vida',
      endereco: 'Avenida Carolina de Abreu Paulino, 66, Bairro dos Abreus, Itapevi, SP',
      lat: -23.5523,
      lng: -46.9458,
    },
    {
      operadora: 'hapvida',
      nome: 'H Family',
      endereco: 'Rua João Santucci, 250, Vila Santa Luzia, Taboão da Serra, SP',
      lat: -23.6147,
      lng: -46.7623,
    },
    {
      operadora: 'hapvida',
      nome: 'PS Barueri',
      endereco: 'Rua Campos Sales, 118, Centro, Barueri, SP',
      lat: -23.5085,
      lng: -46.8758,
    },
    {
      operadora: 'select',
      nome: 'H Cruz Azul de São Paulo',
      endereco: 'Avenida Lins de Vasconcelos, 356, Cambuci, São Paulo, SP',
      lat: -23.5684,
      lng: -46.6267,
    },
    {
      operadora: 'select',
      nome: 'Leforte - Liberdade',
      endereco: 'Rua Barão de Iguape, 209, Liberdade, São Paulo, SP',
      lat: -23.5562,
      lng: -46.6341,
    },
    {
      operadora: 'select',
      nome: 'BP Mirante',
      endereco: 'Rua Martiniano de Carvalho, 965, Bela Vista, São Paulo, SP',
      lat: -23.5658,
      lng: -46.6412,
    },
    {
      operadora: 'select',
      nome: 'H Nove de Julho',
      endereco: 'Rua Peixoto Gomide, 625, Cerqueira César, São Paulo, SP',
      lat: -23.5601,
      lng: -46.6582,
    },
    {
      operadora: 'select',
      nome: 'Samaritano - Paulista',
      endereco: 'Rua Dr. Fausto Ferraz, 204, Bela Vista, São Paulo, SP',
      lat: -23.5651,
      lng: -46.6432,
    },
    {
      operadora: 'select',
      nome: 'Sta Catarina',
      endereco: 'Avenida Paulista, 200, Bela Vista, São Paulo, SP',
      lat: -23.5701,
      lng: -46.6433,
    },
    {
      operadora: 'select',
      nome: 'Blanc',
      endereco: 'Avenida dos Bandeirantes, 679, Vila Olímpia, São Paulo, SP',
      lat: -23.5976,
      lng: -46.6833,
    },
    {
      operadora: 'select',
      nome: 'Dom Alvarenga',
      endereco: 'Avenida Nazaré, 1361, Ipiranga, São Paulo, SP',
      lat: -23.5925,
      lng: -46.6103,
    },
    {
      operadora: 'select',
      nome: 'São Camilo Ipiranga',
      endereco: 'Rua Almirante Lobo, 484, Ipiranga, São Paulo, SP',
      lat: -23.5828,
      lng: -46.6114,
    },
    {
      operadora: 'select',
      nome: 'Sta Rita',
      endereco: 'Rua Cubatão, 1190, Vila Mariana, São Paulo, SP',
      lat: -23.5833,
      lng: -46.6393,
    },
    {
      operadora: 'select',
      nome: 'Cto de Tratamento Bezerra de Menezes - SP',
      endereco: 'Rua Machado Bittencourt, 86, Vila Clementino, São Paulo, SP',
      lat: -23.5992,
      lng: -46.6378,
    },
    {
      operadora: 'select',
      nome: 'Edmundo Vasconcelos',
      endereco: 'Rua Borges Lagoa, 1450, Vila Clementino, São Paulo, SP',
      lat: -23.5982,
      lng: -46.6534,
    },
    {
      operadora: 'select',
      nome: 'Santa Joana',
      endereco: 'Rua do Paraíso, 432, Paraíso, São Paulo, SP',
      lat: -23.5714,
      lng: -46.6414,
    },
    {
      operadora: 'select',
      nome: 'Sta Paula',
      endereco: 'Avenida Santo Amaro, 2468, Brooklin Paulista, São Paulo, SP',
      lat: -23.6015,
      lng: -46.6775,
    },
    {
      operadora: 'select',
      nome: 'Albert Sabin - Lapa',
      endereco: 'Rua Brigadeiro Gavião Peixoto, 123, Lapa, São Paulo, SP',
      lat: -23.5188,
      lng: -46.7214,
    },
    {
      operadora: 'select',
      nome: 'Clínicas FMUSP - Instituto Central',
      endereco: 'Avenida Doutor Enéas de Carvalho Aguiar, 255, Cerqueira César, São Paulo, SP',
      lat: -23.5574,
      lng: -46.669,
    },
    {
      operadora: 'select',
      nome: 'Leforte - Morumbi',
      endereco: 'Rua Três Irmãos, 121, Vila Progredior, São Paulo, SP',
      lat: -23.5912,
      lng: -46.7218,
    },
    {
      operadora: 'select',
      nome: 'São Camilo Pompéia',
      endereco: 'Avenida Pompeia, 1178, Vila Pompéia, São Paulo, SP',
      lat: -23.533,
      lng: -46.6865,
    },
    {
      operadora: 'select',
      nome: 'H São Miguel',
      endereco: 'Rua Severina Leopoldina de Sousa, 44, São Miguel Paulista, São Paulo, SP',
      lat: -23.4958,
      lng: -46.4431,
    },
    {
      operadora: 'select',
      nome: 'IBCC',
      endereco: 'Avenida Alcântara Machado, 2576, Mooca, São Paulo, SP',
      lat: -23.5518,
      lng: -46.5982,
    },
    {
      operadora: 'select',
      nome: 'São Miguel - Ermelino Matarazzo',
      endereco: 'Rua Abel Tavares, 2576, Jardim Belém, São Paulo, SP',
      lat: -23.4913,
      lng: -46.4678,
    },
    {
      operadora: 'select',
      nome: 'Sta Marcelina',
      endereco: 'Rua Santa Marcelina, 177, Vila Carmosina, São Paulo, SP',
      lat: -23.5651,
      lng: -46.4712,
    },
    {
      operadora: 'select',
      nome: 'H Monte Cristo - SP',
      endereco: 'Rua Itapeti, 37, Tatuapé, São Paulo, SP',
      lat: -23.5428,
      lng: -46.5611,
    },
    {
      operadora: 'select',
      nome: 'Sta Virginia',
      endereco: 'Avenida Celso Garcia, 2294, Brás, São Paulo, SP',
      lat: -23.5358,
      lng: -46.5938,
    },
    {
      operadora: 'select',
      nome: 'H e Mat N S do Rosário',
      endereco: 'Rua Doutor Edson de Melo, 357, Vila Maria Alta, São Paulo, SP',
      lat: -23.5134,
      lng: -46.5862,
    },
    {
      operadora: 'select',
      nome: 'Hospital Sao Camilo - Santana',
      endereco: 'Rua Voluntários da Pátria, 3693, Santana, São Paulo, SP',
      lat: -23.4939,
      lng: -46.6322,
    },
    {
      operadora: 'select',
      nome: 'HSANP',
      endereco: 'Rua Voluntários da Pátria, 2786, Santana, São Paulo, SP',
      lat: -23.5011,
      lng: -46.6262,
    },
    {
      operadora: 'select',
      nome: 'Clin Maia (Psiquiatria) - Itapecerica da Serra',
      endereco: 'Estrada João Rodrigues de Moraes, 3560, Lagoa, Itapecerica da Serra, SP',
      lat: -23.7025,
      lng: -46.8711,
    },
    {
      operadora: 'select',
      nome: 'H de Olhos C.R.O',
      endereco: 'Rua Santa Conceição, 51, Vila Progresso, Guarulhos, SP',
      lat: -23.4682,
      lng: -46.5298,
    },
    {
      operadora: 'select',
      nome: 'H e Mat Nova Vida',
      endereco: 'Avenida Carolina de Abreu Paulino, 66, Bairro dos Abreus, Itapevi, SP',
      lat: -23.5415,
      lng: -46.9265,
    },
    {
      operadora: 'select',
      nome: 'H e Mat Cruzeiro do Sul',
      endereco: 'Avenida dos Autonomistas, 2502, Centro, Osasco, SP',
      lat: -23.5376,
      lng: -46.7769,
    },
  ];

  global.REDE_SELECT = REDE_SELECT;
  global.REDE_HAPVIDA = REDE_HAPVIDA;
  global.MAPA_UNIDADES = MAPA_UNIDADES;
})(typeof window !== 'undefined' ? window : globalThis);